### ISSUE TITLE
Doesn't exit, even with --runonce

### ISSUE THREAD

**Issue by Hrxn** [bibanon/BASC-Archiver#33] opened 2016-01-26 04:54 UTC
I'm using the CLI version for Windows from here:
https://github.com/bibanon/BASC-Archiver/releases

I'm on Windows 10 Pro x64 v15.11

Downloading a thread works but the program never finishes. Is this intentional? Continue to watch a thread?

However, even with `--runonce` I had to stop the program with `Ctrl+C`

By the way, is it only 4chan that is supported right now? Honestly, I have no idea about these different image boards and what APIs they provide (if any at all), but I always thought that the majority of these boards run on the same software, more or less..

**Comment by DanielOaks** [comment] 2016-01-26 13:15
By default, it'll keep watching the thread until it 404s or gets `Ctrl+C`'d.

The issue of `--runonce` not exiting is fixed in the latest release. Unfortunately I haven't been able to build and push out a new Windows build of it yet though. Will try to get that done within the next few days, sorry for the hassle!

Right now it's only 4chan. Unfortunately most of them use different software, so need to write code manually for almost each new one. The lack of movement here has mostly just been due to time, and not having enough of it.We have the infrastructure there to support multiple sites, the issue is just getting everything plugged together and working.

The next one to be implemented will probably be `8chan`, then `420chan`. The current `site support` issues we have open can be found [here](https://github.com/bibanon/BASC-Archiver/issues?q=is%3Aissue+is%3Aopen+label%3A%22site+support%22).

Thanks for making the issue -- I'll post in here once that new Windows build is available!

**Comment by Hrxn** [comment] 2016-01-28 08:14
That is good to hear!

And don't worry, no need for a haste, I'm fine.

> “Wisely and slow; they stumble that run fast.”
― William Shakespeare

**Closed** 2018-10-02 05:03 UTC
Labels: bug, confirm fixed, question
